"""add google meet link to meetings

Revision ID: 0a1294ee8557
Revises: 4de8c0d0f7a6
Create Date: 2026-07-07 12:17:01.267890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1294ee8557'
down_revision: Union[str, Sequence[str], None] = '4de8c0d0f7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('google_meet_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'google_meet_link')
    # ### end Alembic commands ###
